# Generated by Django 4.2.3 on 2023-07-13 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_contact_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='category_id',
            new_name='category',
        ),
    ]
