# Generated by Django 4.2.2 on 2023-08-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_contact_patrimonio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='lab_used',
            new_name='lab_usado',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nome',
        ),
    ]
