# Generated by Django 4.2.2 on 2023-08-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_rename_lab_used_contact_lab_usado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='descricao',
        ),
    ]
