# Generated by Django 4.2.2 on 2023-08-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_rename_description_contact_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='category',
            new_name='categoria',
        ),
    ]
